### ISSUE TITLE
Typo in PDF describing the ToRodriguesVector algorithm 

### ISSUE THREAD

**Issue by zygmuntszpak** [imagingbook/imagingbook-calibrate#4]
Thank you for writing this detailed and truly **excellent** exposition of Zhang's camera calibration procedure. 

I noticed a typo in the PDF document describing Algorithm 4.10 (ToRodriguesVector(R)). In particular,  line 2 in the definition of  the vector **p**.  The first component of the vector is given as: R_{2,1} - R_{2,1} whereas it should be R_{2,1} - R_{1,2}.

**Comment by imagingbook** [comment]
I am glad you found this writeup useful and appreciate your comments! The error has been corrected and the updated PDF is already available on [ResearchGate](https://www.researchgate.net/publication/303233579_Zhang%27s_Camera_Calibration_Algorithm_In-Depth_Tutorial_and_Implementation). Thanks much for pointing this out!
